### ISSUE TITLE
浏览器工作原理详读

### ISSUE THREAD

**Issue by shane123qaz** [demozhang1029/reading-notes#14]
- [x] [浏览器工作原理](https://www.html5rocks.com/zh/tutorials/internals/howbrowserswork/)

- [ ] [从输入URL到页面加载的过程](https://segmentfault.com/a/1190000013662126)

**Comment by shane123qaz** [comment]
# 浏览器

### 浏览器工作原理

- 浏览器的主要功能是向服务器发出请求，在窗口中展示各种资源（HTML，PDF，图片等）。

- 浏览器解释并显示HTML文件的方式是在HTML和CSS规范指定的，而这些规范由W3C维护。

- 浏览器的主要组件

  - 用户界面

  - 浏览器引擎

  - 渲染引擎

    - Chrome每个Tab都有单独的渲染引擎实例

    - WebKit是一种开放源码渲染引擎

      - ![WebKit main process](https://www.html5rocks.com/zh/tutorials/internals/howbrowserswork/webkitflow.png)
      - 使用的两种有名的解析生成器
        - 创建词法分析器的 [Flex](http://en.wikipedia.org/wiki/Flex_lexical_analyser) 
        - 创建解析器的 [Bison](http://www.gnu.org/software/bison/)

    - 工作流程

      - ![Parsing HTML to construct DOM tree -> Render tree construction -> Layout of render tree -> Painting the render tree](https://www.html5rocks.com/zh/tutorials/internals/howbrowserswork/flow.png)

      - HTML parser

        - [Play with AST explorer](https://astexplorer.net/)
        - AST(abstract syntax code) - 树上的每个节点都表示源代码中的一种结构.
          - 分词/词法解析：将由字符组成的字符串分解成有意义的代码块,这些代码块统称为**词法单元**(token)。
          - 解析/语法分析：将词法单元流转换成一个由元素嵌套所组成的代表了程序语法结构的树，即抽象语法树。
          - 代码生成：将AST转换成可执行代码的过程

      - CSS parser

        - ![CSS parser](https://www.html5rocks.com/zh/tutorials/internals/howbrowserswork/image023.png)

        - 优先级

          - "style"个数 - ID选择器个数 - 其他元素和伪类个数 - 元素名称和伪元素个数

        - 定位方案：由“position”属性和“float”属性设置的

          - 普通流：值是 static 和 relative

          - 浮动流：float: left/right/inherit

            - 清除浮动

              - 使用带clear属性的空元素

                ```css
                .clear {
                  clear: both
                }
                ```

                ```html
                <p style="float:right;">some text</p>
                <div class="clear"></div>
                ```

              - 使用css的overflow属性 - `overflow:hidden` or `overflow:auto`

                ```html
                <div style="overflow:hidden;">
                  <p style="float:right;">some text</p>  
                </div>
                ```

              - 使用CSS的:after伪元素 - 触发浮动元素父元素的 BFC (Block Formatting Contexts, 块级格式化上下文)

                ```css
                .clearfix {
                  zoom: 1
                }
                
                .clearfix:after {
                	clear:both;
                  visibility:hidden;
                }
                ```

                ```html
                <div class="clearfix">
                  <p style="float:right;">some text</p>  
                </div>
                ```

                

          - 绝对定位：值是 absolute 和 fixed

  - 网络

  - Javascript解释器

  - 用户界面后端

  - 数据持久化
